name = "linkdrop"
type = "javascript"
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-09-20"

[durable_objects]
bindings = [
  { name = "DISCORD", class_name = "Discord" },
  { name = "TWITTER", class_name = "Twitter" },
  { name = "LINKDROP", class_name = "Linkdrop" }
]

[[migrations]]
tag = "v1"
new_classes = ["Discord"]

[[migrations]]
tag = "v2"
new_classes = ["Linkdrop", "Twitter"]

[[migrations]]
tag = "v3"
deleted_classes = ["Discord", "Linkdrop", "Twitter"]

[[migrations]]
tag = "v4"
new_classes = ["Discord", "Linkdrop", "Twitter"]

[[migrations]]
tag = "v5"
deleted_classes = ["Discord", "Linkdrop", "Twitter"]

[[migrations]]
tag = "v6"
new_classes = ["Discord", "Linkdrop", "Twitter"]

[build]
command = "yarn install && yarn build"

[build.upload]
format = "modules"
main = "./index.mjs"
