name = "linkdrop"
type = "javascript"
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-09-20"

[durable_objects]
bindings = [
  { name = "DISCORD", class_name = "Discord" }
]

[[migrations]]
tag = "v1"
new_classes = ["Discord"]

[build]
command = "yarn install && yarn build"

[build.upload]
format = "modules"
main = "./index.mjs"

# [env.production]
# route = 'linkdrop-api.shroomkingdom.net/*'
# zone_id = 'f0cc6af324b9ef33f40a1ef5edf5b1fd'
